记住窗口位置和大小
open-ani/animeko pull request #1110
Opened 2024-10-26 09:45 UTC by NieR4ever

resolve #867

2024-10-26 20:02 UTC, Him188 requested changes

2024-10-26 20:02 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/repository/WindowStateRepository.kt
> +        val Default = SavedWindowState(0f, 0f, width = 1000f, height = 800f)
不能使用固定默认大小. 必须保留现有的默认行为

2024-10-26 20:02 UTC, Him188 commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +            }
Extract function

2024-10-26 20:03 UTC, Him188 commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +                coroutineScope.launch {
这看起来不应该在 DisposableEffect 里加载 flow. 应当在 APP 启动前等待加载好, 然后用历史数据构造 WindowState

2024-10-27 01:37 UTC, NieR4ever commented on app/shared/app-data/src/commonMain/kotlin/data/repository/WindowStateRepository.kt
> +        val Default = SavedWindowState(0f, 0f, width = 1000f, height = 800f)
首次打开 ani 时保存的 WindowState 和 SavedWindowState.Default 相同，此时真正使用的是经过 calculateWindowSize 的 windowState，保留了现有的默认行为
```kt
                    val savedState = windowStateRepository.flow.firstOrNull()?.let { saved ->
                        if (saved == SavedWindowState.Default) return@let null
                        with(density) {
                            WindowState(
                                position = WindowPosition(
                                    x = saved.x.toDp(),
                                    y = saved.y.toDp(),
                                ),
                                size = DpSize(
                                    width = saved.width.toDp(),
                                    height = saved.height.toDp(),
                                ),
                            )
                        }
                    } ?: windowState
```

2024-10-27 21:42 UTC, Him188 commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +        DisposableEffect(true) {
这实际上不会监听 density 变化

```suggestion
val density = LocalDensity.current
        DisposableEffect(density) {
         with(density) {
```

2024-10-27 21:42 UTC, Him188 commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +
```suggestion
        val windowStateRepository = koin.koin.get<WindowStateRepository>()
        runBlocking {
            windowState.size = windowStateRepository.flow.firstOrNull()
        }
```

直接这个吧

2024-10-27 21:42 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/repository/WindowStateRepository.kt
> +    val flow: Flow<SavedWindowState>
```suggestion
    val flow: Flow<SavedWindowState?>
```
没保存的话就用 null 吧

2024-10-27 21:42 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/repository/WindowStateRepository.kt
> +        val Default = SavedWindowState(0f, 0f, width = 1000f, height = 800f)
default to null
```suggestion
```

2024-10-27 21:42 UTC, Him188 commented
测试OK

2024-10-28 03:16 UTC, NieR4ever commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +
需要借助 density 所以不能在这里操作 windowState

2024-10-28 09:13 UTC, Him188 reviewed
还有一个问题, 如果在外接显示器 (分辨率更大) 的时候保存一个状态, 拔掉显示器后恢复状态, 窗口是不是会显示在屏幕外部.

另外最好还要加一个最小大小限制, 随便什么就行, 只是限制启动时不能只有一丁点

2024-10-28 11:10 UTC, NieR4ever commented
> 还有一个问题, 如果在外接显示器 (分辨率更大) 的时候保存一个状态, 拔掉显示器后恢复状态, 窗口是不是会显示在屏幕外部.

会显示在屏幕外部并且无法操作

2024-10-28 11:25 UTC, Him188 commented
> 会显示在屏幕外部并且无法操作

那是不可以的，需要限制位置

2024-10-28 21:44 UTC, Him188 commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +            }
如果它位置或大小有任意一项不合规, 就采用默认设置 (就相当于忽略保存的状态), 比较好吧

2024-10-30 12:58 UTC, Him188 approved these changes

2024-10-30 12:58 UTC, merged