Async RPC call of Android Binder
open-ani/animeko pull request #1201
Opened 2024-11-15 09:42 UTC by StageGuard

此 PR 旨在消除 service proxy 的 `runBlocking`，提高 service 吞吐量

### 目前问题

例如，`IRemoteTorrentDownloader.aidl` 中的 `startRemoteDownload` 接口为

```aidl
IRemoteTorrentSession startRemoteDownload(in PEncodedTorrentInfo data, in String overrideSaveDir);
```

这个接口对应了 `TorrentDownloader` 的 `startDownload` 函数，是一个 suspend 函数

```kotlin
suspend fun startDownload(
    data: EncodedTorrentInfo,
    parentCoroutineContext: CoroutineContext = EmptyCoroutineContext,
    overrideSaveDir: SystemPath? = null,
): TorrentSession
```

目前在 client 的调用实现为

```kotlin
override suspend fun startDownload(
    data: EncodedTorrentInfo,
    parentCoroutineContext: CoroutineContext,
    overrideSaveDir: SystemPath?
): TorrentSession {
    return remote.startRemoteDownload(data.toParceled(), overrideSaveDir?.absolutePath)
}
```

在 service 的实现为

```kotlin
override fun startRemoteDownload(data: PEncodedTorrentInfo?, overrideSaveDir: String?): IRemoteTorrentSession? {
    val session = runBlocking { 
        actualServiceTorrentDownloader.startDownload(
            withContext(Dispatchers.IO_) { data.toEncodedTorrentInfo() },
            overrideSaveDir = overrideSaveDir?.run { Path(this).inSystem },
        ) 
    }
    return TorrentSessionProxy(session, this, scope.coroutineContext)
}
```

client 调用 `startRemoteDownload` 时需要等待 service 实现中的 `runBlocking` 执行完成才会返回结果，如果 `runBlocking` 执行了很长时间，那 client 调用端会一直等待结果而阻塞，service 实现也会因为 `runBlocking` 而不能使用当前的 binder 线程继续处理其他 client 调用

## 新变化

此 PR 将 `startRemoteDownload` AIDL 接口改为如下回调形式

```aidl
IDisposableHandle startRemoteDownload(in PEncodedTorrentInfo data, in String overrideSaveDir, in RemoteContinuation cont);
```

```aidl
interface RemoteContinuation {
    void resume(in IRemoteTorrentSession value);
    void resumeWithException(in RemoteContinuationException exception);
}
```

其中，`IDisposableHandle` 用于处理 service 取消协程的动作，client 取消协程后通过 `IDisposableHandle` 通知 service 同样取消对应处理协程，`RemoteContinuation` 用于回调结果

如此而来，client 通过 `suspendCancellableCoroutine` 就可以比较轻易地实现回调 API 的挂起

```kotlin
override suspend fun startDownload(
    data: EncodedTorrentInfo,
    parentCoroutineContext: CoroutineContext,
    overrideSaveDir: SystemPath?
): TorrentSession = suspendCancellableCoroutine { cont ->
    val disposable = remote.startRemoteDownload(
        data.toParceled(), 
        overrideSaveDir?.absolutePath,
        object : ContTorrentDownloaderStartDownload.Stub() {
            override fun resume(value: IRemoteTorrentSession?) {
                cont.resume(value)
            }   

            override fun resumeWithException(exception: RemoteContinuationException?) {
                cont.resumeWithException(exception)
            }

        }
    )
    
    cont.invokeOnCancellation { disposable.dispose() }
```

service 也可以去除 `runBlocking`，并且快速返回结果

```kotlin
override fun startRemoteDownload(
    data: PEncodedTorrentInfo?,
    overrideSaveDir: String?,
    cont: RemoteContinuation?
): IDisposableHandle? {
    if (data == null) return null
    if (cont == null) return null

    val job = scope.launch(
        CoroutineExceptionHandler { _, throwable ->
            cont.resumeWithException(throwable.toRemoteContinuationException())
        } + Dispatchers.IO_,
    ) {
        val result = delegate.startDownload(
            withContext(Dispatchers.IO_) { data.toEncodedTorrentInfo() },
            overrideSaveDir = overrideSaveDir?.run { Path(this).inSystem },
        )
        cont.resume(TorrentSessionProxy(result, this@TorrentDownloaderProxy, scope.coroutineContext))
    }

    return DisposableHandleProxy { job.cancel() }
}
```

2024-11-15 10:04 UTC, StageGuard commented
经测试改了之后大幅度加速了 `[resolveDownloadingFile]: Still waiting to get file` 的等待时间

2024-11-15 11:40 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +): T = suspendCancellableCoroutine { cont ->
convert 没必要. 可以直接 return P.

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    crossinline convert: (P) -> T,
这个 convert 也可以去掉, future 可以用 thenApply 相当于 map

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    ) -> IDisposableHandle?,
这东西返回 null 的话下面一定会抛出异常, 对吗

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +        while (!remote.compareAndSet(null, newRemote));
remote.update {}

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
>          val newRemote = getRemote()
not thread safe

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    private fun setRemote(): Deferred<I> = scope.async {
生命周期感觉比较乱, 应当由 RetryRemoteCall 自己持有 scope?

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    ) -> IDisposableHandle?,
```suggestion
    crossinline call: I.(
        cont: RemoteContinuation
    ) -> IDisposableHandle?,
```
```kotlin
interface RemoteContinuation<T> {
    fun resume(value: T)
    fun resumeWithException(e: Throwable)
}
```

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +suspend inline fun <I : IInterface, T> RemoteCall<I>.callSuspendCancellable(
```suggestion
suspend inline fun <I : IInterface, T : Any> RemoteCall<I>.callSuspendCancellable(
```

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +        val call1 = random.nextInt()
unused

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +                synchronized(lock) { setRemote() }.await()
setRemote 会 launch, 这个 synchronized 实际上没有意义

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +                    cont.resumeWithException(CancellationException("Remote resume a null value."))
```suggestion
                    cont.resumeWithException(CancellationException("Remote resume a null value."))
```

CancellationException 语义正确吗?

自己构造 CancellationException 通常来说是错误的

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +                    cont.resumeWithException(CancellationException("Remote resume a null value."))
这里可能要用 IllegalStateException?

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +                    exception?.smartCast() ?: Exception("Remote resume a null exception."),
```suggestion
                    exception?.smartCast() ?: IllegalStateException("Remote resume a null exception."),
```

那是不是实际上不应该允许 exception 为 null (类型上)

2024-11-16 13:37 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +        cont.resumeWithException(CancellationException("Remote disposable is null."))
is CancellationException correct?

2024-11-16 13:41 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/service/AniTorrentService.kt
> +        Dispatchers.Default + CoroutineName("AniTorrentService") +
```suggestion
    override val coroutineContext: CoroutineContext =
        Dispatchers.Default + CoroutineName("AnitorrentService") + 
```

Anitorrent 其实是一个单词

2024-11-16 13:41 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteTorrentSession.kt
> +    RemoteCall<IRemoteTorrentSession> by RetryRemoteCall(fetchRemoteScope, getRemote),
我觉得应该传入 `val remote: RemoteCall<IRemoteTorrentSession>`

2024-11-16 13:41 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteTorrentSession.kt
>      connectivityAware: ConnectivityAware,
为什么同时有 RemoteCall 和 connectivityAware

2024-11-16 13:41 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/service/proxy/TorrentSessionProxy.kt
> +            if (!isConnected) return@launch
这里没有 resume cont, 导致无限等待

2024-11-16 13:41 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/service/proxy/TorrentSessionProxy.kt
> +                if (!isConnected) return@CoroutineExceptionHandler
没有 resume

2024-11-16 13:42 UTC, Him188 reviewed
`RemoteCall` 改名叫 `RemoteObject` 是不是更好一点

`remoteObject.callSuspend { foo() }` 听起来更合理

2024-11-16 13:54 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    ) -> IDisposableHandle?,
一定要获取到 disposable handle 才是 rpc 调用成功

2024-11-16 14:00 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
>          val newRemote = getRemote()
其实是 threadsafe的，这个只在下面call用了，还是加锁的，

2024-11-16 14:05 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    ) -> IDisposableHandle?,
那就应该改成 `reject: (RemoteContinuationException) -> Unit`, 让调用方抛异常?

2024-11-16 14:09 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +    private fun setRemote(): Deferred<I> = scope.async {
现在是持有的

2024-11-16 14:17 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +                    cont.resumeWithException(CancellationException("Remote resume a null value."))
好像确实是

2024-11-16 14:22 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteCall.kt
> +                    exception?.smartCast() ?: Exception("Remote resume a null exception."),
可能是 null，rpc 如果失败了会 null

2024-11-16 14:23 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/service/AniTorrentService.kt
> +        Dispatchers.Default + CoroutineName("AniTorrentService") +
我知道 Anitorrent 指的是我们的 torrent 引擎，但是这里表示的是 Animeko Torrent 服务

2024-11-16 14:34 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/service/proxy/TorrentSessionProxy.kt
> +                if (!isConnected) return@CoroutineExceptionHandler
同上

2024-11-16 14:39 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteTorrentSession.kt
>      connectivityAware: ConnectivityAware,
connectivityAware 只有一个实例，RemoteCall 需要创建很多实例

2024-11-16 14:40 UTC, StageGuard commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteTorrentSession.kt
>      connectivityAware: ConnectivityAware,
connectivityAware 在 service 和 client 都用， RemoteCall 只在 client 用

2024-11-16 14:54 UTC, Him188 requested changes

2024-11-16 14:54 UTC, Him188 commented on app/shared/app-data/src/androidMain/kotlin/domain/torrent/client/RemoteObject.kt
> +        newRemote
race

2024-11-16 14:54 UTC, Him188 approved these changes

2024-11-16 16:19 UTC, merged