添加 nsfw 设置选项
open-ani/animeko pull request #1294
Opened 2024-12-05 00:05 UTC by NieR4ever

resolve #1282

2024-12-06 02:45 UTC, StageGuard requested changes
除了搜索，其他能获取内容的地方也需要过滤，例如主页和收藏

2024-12-06 02:45 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/main/SearchViewModel.kt
> +                    subjects.filter { if (nsfwMode == NSFWMode.HIDE) !it.nsfw else true }
```suggestion
                    if (nsfwMode != NSFWMode.HIDE) return subjects
                     subjects.filter { !it.nsfw }
```

2024-12-06 02:45 UTC, StageGuard commented on app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/search/SearchPage.kt
>  ) {
再加一个 overlay 文字显示类似 "此内容 nsfw" 之类的提示？

2024-12-06 08:25 UTC, NieR4ever commented
![PixPin_2024-12-06_16-23-59](https://github.com/user-attachments/assets/abd3760b-6298-4ab3-9c42-c4ee94802881)
![PixPin_2024-12-06_16-24-15](https://github.com/user-attachments/assets/c4682884-5898-4bec-803e-c0ddada5598a)

2024-12-06 09:37 UTC, Him188 commented
我觉得无需显示文字提示，另外blur的强度不够

2024-12-06 09:52 UTC, StageGuard commented
1. 模糊图片的边缘似乎有问题
2. 模糊半径有点小了
3. 建议整个卡片都遮住，遮之前先加一层透明黑色或透明白色的遮罩，避免提示文字看不清
4. 文字提示改为“此内容不适合显示”，然后在卡片右下角或者其他地方添加一个眼睛的 icon，点一下强制显示

2024-12-06 09:57 UTC, StageGuard commented
我觉得你可以抽象出一个 NsfwMask composable 或者 Modifier

2024-12-06 10:06 UTC, Him188 commented
文字没必要显示吧，只要模糊了大家都懂是为什么

2024-12-06 10:08 UTC, StageGuard commented
> 文字没必要显示吧，只要模糊了大家都懂是为什么

因为我建议整个卡片都模糊，所以还是需要文字提示的

2024-12-07 03:33 UTC, NieR4ever commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +                contentModifier.blur(radius = 12.dp, edgeTreatment = BlurredEdgeTreatment.Unbounded)
NSFWMask 里 edgeTreatment 用 Unbounded 模糊了边界，会产生一种下沉的效果
![PixPin_2024-12-07_10-48-53](https://github.com/user-attachments/assets/6f80ec22-b0a8-43ab-ba09-fa17a5f13524)
如果需要边界的话只能在 clip() 之后再使用 blur()，否则不会有圆角效果，有更好的解决方法吗

2024-12-07 03:39 UTC, StageGuard commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +            content(
```suggestion
            Box(modifier = Modifier.blur()) {
                content()
            }
```

2024-12-07 03:40 UTC, StageGuard commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +                contentModifier.blur(radius = 12.dp, edgeTreatment = BlurredEdgeTreatment.Unbounded)
那就先 clip 再 blur 吧

2024-12-07 03:57 UTC, NieR4ever commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +                contentModifier.blur(radius = 12.dp, edgeTreatment = BlurredEdgeTreatment.Unbounded)
每个组件的 shape 都是自己决定的，对于搜索页的 subject 需要将 NSFWMaskState 传入到 SubjectItemLayout 中才能在 clip 之后应用 blur，这会使 SubjectItemLayout 变复杂

2024-12-07 10:30 UTC, NieR4ever commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +                contentModifier.blur(radius = 12.dp, edgeTreatment = BlurredEdgeTreatment.Unbounded)
@Him188 你怎么看

2024-12-07 10:34 UTC, Him188 commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +                contentModifier.blur(radius = 12.dp, edgeTreatment = BlurredEdgeTreatment.Unbounded)
让每个组件自己构造 `Modifier.nsfwBlur(NsfwMaskState, shape)` 呢

2024-12-07 15:25 UTC, NieR4ever commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/CarouselItem.kt
>          }
这里改动了 clip() 的范围

2024-12-07 16:25 UTC, StageGuard commented
有效果图吗

2024-12-08 01:32 UTC, NieR4ever commented
![PixPin_2024-12-08_08-54-06](https://github.com/user-attachments/assets/8973d255-469c-4bbe-96a4-43a970be2ac1)
![PixPin_2024-12-08_08-54-43](https://github.com/user-attachments/assets/d290310e-54bc-4a3d-b843-876a6a0363bb)
![PixPin_2024-12-08_09-01-10](https://github.com/user-attachments/assets/0afe1ad1-7a5b-47d7-bd47-8186ef32348f)
![PixPin_2024-12-08_09-01-52](https://github.com/user-attachments/assets/74011ec7-e734-4125-b9f3-b53c56f53192)
![PixPin_2024-12-08_09-28-23](https://github.com/user-attachments/assets/074883e9-0acd-4f7a-b455-65e4ceafbc2f)
![PixPin_2024-12-08_09-28-44](https://github.com/user-attachments/assets/1845539d-f15e-4f85-86f1-fc43500bafa3)

2024-12-08 02:39 UTC, StageGuard reviewed
目前的设计比较奇怪，我不仅给需要遮住的组件套上 NSFWMask，还要给里面对应的东西加 modifier。这个是有副作用的，强制耦合了 NSFWMask 和使用 NSFWMask 的组件，这意味着我在其他地方使用组件也需要判断 nsfw state，即使我没有给他外层套上 NSFWMask。
期望只应该 expose NSFWMask 和 NSFWMaskState，不要有 Modifier.nsfwBlur。想遮住哪个组件，只需要套上 NSFWMask，不应该改动组件。
如果担心 clip 没办法传递，那可以把 clip 参数添加到 NSFWMask。

2024-12-08 02:39 UTC, StageGuard commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/layout/CarouselItem.kt
> +    Box(modifier.clip(maskShape).nsfwBlur(LocalNSFWMaskState.current)) {
不应该耦合 carousel foundation

2024-12-08 02:39 UTC, StageGuard commented on app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/search/SubjectItem.kt
> +            .nsfwBlur(LocalNSFWMaskState.current)
不应该耦合 SubjectCollectionItem foundation

2024-12-08 02:48 UTC, StageGuard commented
目前看起来挺不错了，

> ![PixPin_2024-12-08_08-54-06](https://private-user-images.githubusercontent.com/65274728/393556777-8973d255-469c-4bbe-96a4-43a970be2ac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjU4OTEsIm5iZiI6MTczMzYyNTU5MSwicGF0aCI6Ii82NTI3NDcyOC8zOTM1NTY3NzctODk3M2QyNTUtNDY5Yy00YmJlLTk2YTQtNDNhOTcwYmUyYWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAyMzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NDBiNmRhYjI4MmJmODRhMWQ3YjAyZjM0ZWIxOWU1ZGQxOGNkNGI3ZjRmYmQzNDljMDU1Nzk3NDU2NGFkMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.76WqXn1C9wTu3hoZgoZIqUBWn09KdSnu8in5O24nOZ4) ![PixPin_2024-12-08_08-54-43](https://private-user-images.githubusercontent.com/65274728/393556785-d290310e-54bc-4a3d-b843-876a6a0363bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjU4OTEsIm5iZiI6MTczMzYyNTU5MSwicGF0aCI6Ii82NTI3NDcyOC8zOTM1NTY3ODUtZDI5MDMxMGUtNTRiYy00YTNkLWI4NDMtODc2YTZhMDM2M2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAyMzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYzIxYTM4ZDA0ZjM0YWEwMjVhMjU2ZjJiODI2NjNiZTVkN2U2MjJkYzAzZDM1NmMzODZmMmVlYTk0YzQ4ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WFcN_qE4PLpSu9lUb0vL7jf7SElEGtIkrwdigD_TIEg) ![PixPin_2024-12-08_09-01-10](https://private-user-images.githubusercontent.com/65274728/393556787-0afe1ad1-7a5b-47d7-bd47-8186ef32348f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjU4OTEsIm5iZiI6MTczMzYyNTU5MSwicGF0aCI6Ii82NTI3NDcyOC8zOTM1NTY3ODctMGFmZTFhZDEtN2E1Yi00N2Q3LWJkNDctODE4NmVmMzIzNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAyMzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjY2YzMTJiMmZiNTkyNzM2OGNhNDZkNDU4ZjI3MjRlNmNmNTMxZjk5MDgxYzhhZGZmZmM4NTY2MTM4MTNmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OsarEvpB3-bK3fVGnNcnQ1HQL5kh3jc3OZ2Dtqn5oYc) ![PixPin_2024-12-08_09-01-52](https://private-user-images.githubusercontent.com/65274728/393556790-74011ec7-e734-4125-b9f3-b53c56f53192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjU4OTEsIm5iZiI6MTczMzYyNTU5MSwicGF0aCI6Ii82NTI3NDcyOC8zOTM1NTY3OTAtNzQwMTFlYzctZTczNC00MTI1LWI5ZjMtYjUzYzU2ZjUzMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAyMzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNzY5OWViY2E4MjhiZDVjZGUwYzI4MTJiOGMyMmJkNzFhOTU4NDI0MTYwNDEwZTlkMmM3YTA0OTU1ZjhjZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fUxcj2SkiRlDumiYFHHgIVioSf9dmx-XXLX1rKHDWIU) ![PixPin_2024-12-08_09-28-23](https://private-user-images.githubusercontent.com/65274728/393556793-074883e9-0acd-4f7a-b455-65e4ceafbc2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjU4OTEsIm5iZiI6MTczMzYyNTU5MSwicGF0aCI6Ii82NTI3NDcyOC8zOTM1NTY3OTMtMDc0ODgzZTktMGFjZC00ZjdhLWI0NTUtNjVlNGNlYWZiYzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAyMzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDM0OTk1MDZiM2RiNmYzOGVkYjRkMmRlNWE3YjRhYTRmN2E4NzY1ZjBmNjY2OGRjYTA0MDY4YzE3NzljMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hfY4ORDTPi9jeXLUc7dB43XlP9jK5bEiF3Rw3WWvrT4) ![PixPin_2024-12-08_09-28-44](https://private-user-images.githubusercontent.com/65274728/393556799-1845539d-f15e-4f85-86f1-fc43500bafa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MjU4OTEsIm5iZiI6MTczMzYyNTU5MSwicGF0aCI6Ii82NTI3NDcyOC8zOTM1NTY3OTktMTg0NTUzOWQtZjE1ZS00Zjg1LTg2ZjEtZmM0MzUwMGJhZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAyMzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZTI5NWFiNzllYjRhZmJmNzBkM2NmYTkzYjE1M2IwZmI1ZDQxZDRhM2JjMmY4NjdjYmUzMGYwNTdjYjc4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s1HX9DmBMhcWWjsKrm_cGQskaIBdqnLStTOM1bOPPxw)

目前看起来挺不错了，不过还有点小问题。因为是文字在上图标在下，用 center vertically 会觉得有点头重脚轻了，可以适当把布局下移一些（例如黄金比例）。

2024-12-08 03:53 UTC, NieR4ever commented
> 目前的设计比较奇怪，我不仅给需要遮住的组件套上 NSFWMask，还要给里面对应的东西加 modifier。这个是有副作用的，强制耦合了 NSFWMask 和使用 NSFWMask 的组件，这意味着我在其他地方使用组件也需要判断 nsfw state，即使我没有给他外层套上 NSFWMask。 期望只应该 expose NSFWMask 和 NSFWMaskState，不要有 Modifier.nsfwBlur。想遮住哪个组件，只需要套上 NSFWMask，不应该改动组件。 如果担心 clip 没办法传递，那可以把 clip 参数添加到 NSFWMask。

> 这意味着我在其他地方使用组件也需要判断 nsfw state，即使我没有给他外层套上 NSFWMask。

这种情况 nsfw state 是有默认值的，默认不使用遮罩

> 如果担心 clip 没办法传递，那可以把 clip 参数添加到 NSFWMask。

在使用 NSFWMask 的位置可能是没办法获得 shape 的，像搜索页的 subject 除非直接在 SubjectItemLayout 里使用 NSFWMask，这会导致更高程度的耦合

> 想遮住哪个组件，只需要套上 NSFWMask，不应该改动组件。

除非放弃描边，否则不改动组件应该是不可能的

2024-12-08 03:56 UTC, NieR4ever commented
Modifier.blur() 在 android 10 没有效果

2024-12-08 05:51 UTC, StageGuard requested changes
我帮你解决了耦合的问题，还有其他问题需要解决

2024-12-08 05:51 UTC, StageGuard commented on app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/followed/FollowedSubjectsLazyRow.kt
> +            val nsfwMaskState = remember { NSFWMaskState(item?.subjectInfo?.nsfw ?: false, blurEnabled) }
状态需要保存到 view model 中

2024-12-08 05:51 UTC, StageGuard commented on app/shared/ui-exploration/src/commonMain/kotlin/ui/exploration/search/SearchPage.kt
> +                val nsfwMaskState = NSFWMaskState(info.nsfw, blurEnabled)
状态需要保存到 view model 中

2024-12-08 05:51 UTC, StageGuard commented on app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/CollectionPage.kt
> +                            val nsfwModeState = remember {
状态需要保存到 view model 中

2024-12-08 05:53 UTC, StageGuard requested changes

2024-12-08 05:53 UTC, StageGuard commented on app/shared/ui-foundation/src/commonMain/kotlin/ui/foundation/widgets/NSFWMask.kt
> +                Text("此内容不适合展示", modifier = Modifier.basicMarquee())
不使用轮播显示，显示不下就多行

2024-12-08 23:53 UTC, Him188 commented
Request me when ready

2024-12-09 16:00 UTC, NieR4ever commented
android 11 以下的效果
![PixPin_2024-12-09_23-57-55](https://github.com/user-attachments/assets/56cca57b-4079-4433-9877-13b09214e941)
![PixPin_2024-12-09_23-58-42](https://github.com/user-attachments/assets/bce57736-e7f2-4a64-a762-829724298b26)

2024-12-10 02:14 UTC, StageGuard approved these changes

2024-12-10 14:05 UTC, Him188 commented on app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/UserCollectionsViewModel.kt
> +        nsfwModeState = nsfwSettingFlow.produceState(NSFWMode.DISPLAY),
default value problem (跟上面我评论的一样)

2024-12-10 14:06 UTC, Him188 commented on app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/UserCollectionsViewModel.kt
> +    ) { nsfwMode, pagingData ->
应当由 pager 来处理 nsfw 过滤吧 (数据库直接过滤), 否则会有分页加载数量的问题

2024-12-10 14:07 UTC, Him188 commented on app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/UserCollectionsViewModel.kt
>          collectionCountsState = subjectCollectionRepository.subjectCollectionCountsFlow().produceState(null),
没有修改这个? 那计数是可能会大于实际展示的数量的?

2024-12-10 14:14 UTC, Him188 commented on app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/CollectionPage.kt
> +                                    state.nsfwModeState.value == NSFWMode.BLUR,
blur 状态需要由 pager 返回, 也就是封装在分页加载逻辑中. 期望的流程是: UI 显示转圈 (查询数据库和读取配置中) -> UI 下一帧直接显示正确的 blur 状态. 

而目前你的实现看起来是一个异步读取配置得到的 state.nsfwModeState, 这可能导致 UI 有那么一帧会显示一个初始状态的 blur. 应该把 nsfwModeState 封装到 collection (SubjectCollectionInfo) 里, 并且改成 immutable? 

CC @StageGuard

2024-12-10 14:29 UTC, StageGuard commented on app/shared/ui-subject/src/commonMain/kotlin/ui/subject/collection/CollectionPage.kt
> +                                    state.nsfwModeState.value == NSFWMode.BLUR,
确实，会有这种情况，所以我之前说应该把状态存到 vm 里，或者由 vm 提供

2024-12-10 14:32 UTC, StageGuard commented on app/shared/app-data/src/commonMain/kotlin/data/models/preference/UISettings.kt
> +    val nsfwMode: NSFWMode = NSFWMode.HIDE,
先默认改成隐藏吧，之后重写欢迎界面需要让用户选择

2024-12-11 00:02 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/models/preference/UISettings.kt
> +    val nsfwMode: NSFWMode = NSFWMode.HIDE,
需要在 repository 层 pager 处理过滤

2024-12-16 20:55 UTC, Him188 commented
这个是不是还在等我来着

2024-12-17 00:31 UTC, NieR4ever commented
异步读取配置的问题不知道怎么解决

2024-12-17 16:07 UTC, Him188 commented
我解决了问题, 现在是在 repository 里读出好了配置才交给 UI. 还简化 (删除) 了 `NsfwMaskState`, 现在它只需要一个 mutableStateOf

2024-12-19 03:16 UTC, Him188 commented
Ping @StageGuard

2024-12-19 04:39 UTC, StageGuard requested changes

2024-12-19 04:39 UTC, StageGuard commented on app/shared/app-data/src/commonMain/kotlin/data/repository/subject/FollowedSubjectsRepository.kt
> +        combine(
nsfwModeSettingsFlow 改变会导致重新查询 repo，需要 combine 到下面来缓存

2024-12-19 13:08 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/repository/subject/FollowedSubjectsRepository.kt
> +        combine(
fixed

2024-12-19 13:08 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/repository/subject/FollowedSubjectsRepository.kt
> +        combine(
fixed

2024-12-19 17:11 UTC, StageGuard approved these changes

2024-12-19 17:36 UTC, merged